services:
  singbox:
    restart: always
    container_name: sing-box
    image: ghcr.io/sagernet/sing-box:v1.9.0-alpha.13
    network_mode: host
    volumes:
      - ./config.json:/etc/sing-box/config.json:ro
    command: 
      - -C
      - /etc/sing-box
      - run
    logging:
      options:
        max-size: "20m"
