services:
  vehicle:
    restart: always
    container_name: vehicle
    image: miniluv/vehicle:v0.0.3
    network_mode: host
    volumes:
      - ./config.json:/etc/vehicle/config.json:ro
    command:
      - -C
      - /etc/vehicle
      - run
    logging:
      options:
        max-size: "10m"
